### ISSUE TITLE
Upgrade to / support new version `lit@2`

### ISSUE THREAD

**Issue by thescientist13** [hutchgrant/evergreen-web-components#33]
There's an upcoming version of **lit-html** and **lit-element** where everything will get consolidated under a new top level [`lit` package](https://www.npmjs.com/package/lit).

As part of the [upgrade process](https://lit.dev/docs/releases/upgrade/#update-packages-and-import-paths), it is required to drop the old package name references and change `import` statements.  For this reason, in the Greenwood website project, we will not be able to support **evergreen-web-components** [unless they are also upgraded to use the new `lit` package](https://github.com/ProjectEvergreen/greenwood/pull/611).

Hopefully not too much effort, and will try and take a look at making the change myself as the APIs of **lit-html** and **lit-element** should be mostly backwards compatible, and so far things we working well in the Greenwood website.

----

I assume this would initiate a major version bump, which would seem reasonable to me.

Let me know your thoughts!

**Comment by hutchgrant** [comment]
This looks like a good idea. I'll look into it soon.

**Comment by hutchgrant** [comment]
Updated to lit 2.0 all packages. No breaking changes.
